### ISSUE TITLE
When running jsonschema against the official JSON-schema test suite it causes side-effects. It alters the data.

### ISSUE THREAD

**Issue by Muscula** [tdegrunt/jsonschema#107]
When running jsonschema against the official JSON-schema test suite, running the tests:
- `multiple dependencies subschema, valid`
- `multiple dependencies subschema, wrong type`
- `multiple dependencies subschema, wrong type other`
- `multiple dependencies subschema, wrong type both`

has side-effects on the data. The data is altered by jsonschema.

https://github.com/Muscula/json-schema-benchmark/blob/master/reports/jsonschema-side-effects.md

Edit: I just added some more detail to the error report, to make it easier for you to see what's going on, and to reproduce the error.

**Comment by jRiest** [comment]
Just ran into this issue. This also means we cannot validate immutable (frozen) objects.

Running this:

    var jsonschema = require('jsonschema');
    var deepFreeze = require('deep-freeze');

    var data = {
      x: [
        {
          id: 1
        }
      ]
    };

    deepFreeze(data);

    jsonschema.validate(data, {
      type: 'object',
      properties: {
        x: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              id: {
                type: 'number'
              }
            }
          }
        }
      }
    });

results in an error:

    /path/to/project/node_modules/jsonschema/lib/attribute.js:291
        result.instance[i] = res.instance;
                           ^
    TypeError: Cannot assign to read only property '0' of [object Object]
        at /path/to/project/node_modules/jsonschema/lib/attribute.js:291:24
        ...

**Comment by Acubed** [comment]
Yeah, the passed instance shouldn't be modified under any circumstances. Well... mostly. We do offer the "rewrite" option, which right now modifies the passed-in instance, IF the rewrite rule makes any change. It looks like arrays don't test for a modification, though.

(Perhaps "rewrite" should make a copy, but there's some questions around what if a property is matched against multiple sub-schemas, e.g. properties, patternProperties, and allOf.)

This should be fixed in 4497ac2c7bb09be0294ea37bbbf47caab0da4852, can you verify? Thanks!

**Comment by Muscula** [comment]
It looks like you are still adding an `id`-property to every schema

https://github.com/Muscula/json-schema-benchmark/blob/master/reports/json-model-side-effects.md

**Comment by Muscula** [comment]
I still have this side-effect:
```js
var data = {
	"foo": 1,
	"bar": 2
};
var schema = {
	"dependencies": {
		"bar": {
			"properties": {
				"foo": {
					"type": "integer"
				},
				"bar": {
					"type": "integer"
				}
			}
		}
	}
};
require('../jsonschema').validate(data, schema);
console.log(data)
// { foo: 1, bar: [Circular] }
```

`../jsonschema` contains a fork I just did (you did not publish this fix to npm did you?)

More tests here: https://github.com/Muscula/json-schema-benchmark/blob/master/reports/jsonschema-side-effects.md

**Comment by Acubed** [comment]
@Muscula Oh there's another fix required too... This time I added a test, fix is in Git at b61cc4a7decb6357059ad294a9d07e9bfeb793d1. Can you verify this again?

**Comment by Muscula** [comment]
Yes the problem seems fixed in the latest master.
